(cl:defpackage cob_kinematics-srv
  (:use )
  (:export
   "GETPOSITIONIKEXTENDED"
   "<GETPOSITIONIKEXTENDED-REQUEST>"
   "GETPOSITIONIKEXTENDED-REQUEST"
   "<GETPOSITIONIKEXTENDED-RESPONSE>"
   "GETPOSITIONIKEXTENDED-RESPONSE"
  ))

