; Auto-generated. Do not edit!


(cl:in-package cob_pick_place_action-msg)


;//! \htmlinclude CobPickResult.msg.html

(cl:defclass <CobPickResult> (roslisp-msg-protocol:ros-message)
  ((success
    :reader success
    :initarg :success
    :type std_msgs-msg:Bool
    :initform (cl:make-instance 'std_msgs-msg:Bool))
   (cob_pick_error_string
    :reader cob_pick_error_string
    :initarg :cob_pick_error_string
    :type cl:string
    :initform ""))
)

(cl:defclass CobPickResult (<CobPickResult>)
  ())

(cl:defmethod cl:initialize-instance :after ((m <CobPickResult>) cl:&rest args)
  (cl:declare (cl:ignorable args))
  (cl:unless (cl:typep m 'CobPickResult)
    (roslisp-msg-protocol:msg-deprecation-warning "using old message class name cob_pick_place_action-msg:<CobPickResult> is deprecated: use cob_pick_place_action-msg:CobPickResult instead.")))

(cl:ensure-generic-function 'success-val :lambda-list '(m))
(cl:defmethod success-val ((m <CobPickResult>))
  (roslisp-msg-protocol:msg-deprecation-warning "Using old-style slot reader cob_pick_place_action-msg:success-val is deprecated.  Use cob_pick_place_action-msg:success instead.")
  (success m))

(cl:ensure-generic-function 'cob_pick_error_string-val :lambda-list '(m))
(cl:defmethod cob_pick_error_string-val ((m <CobPickResult>))
  (roslisp-msg-protocol:msg-deprecation-warning "Using old-style slot reader cob_pick_place_action-msg:cob_pick_error_string-val is deprecated.  Use cob_pick_place_action-msg:cob_pick_error_string instead.")
  (cob_pick_error_string m))
(cl:defmethod roslisp-msg-protocol:serialize ((msg <CobPickResult>) ostream)
  "Serializes a message object of type '<CobPickResult>"
  (roslisp-msg-protocol:serialize (cl:slot-value msg 'success) ostream)
  (cl:let ((__ros_str_len (cl:length (cl:slot-value msg 'cob_pick_error_string))))
    (cl:write-byte (cl:ldb (cl:byte 8 0) __ros_str_len) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 8) __ros_str_len) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 16) __ros_str_len) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 24) __ros_str_len) ostream))
  (cl:map cl:nil #'(cl:lambda (c) (cl:write-byte (cl:char-code c) ostream)) (cl:slot-value msg 'cob_pick_error_string))
)
(cl:defmethod roslisp-msg-protocol:deserialize ((msg <CobPickResult>) istream)
  "Deserializes a message object of type '<CobPickResult>"
  (roslisp-msg-protocol:deserialize (cl:slot-value msg 'success) istream)
    (cl:let ((__ros_str_len 0))
      (cl:setf (cl:ldb (cl:byte 8 0) __ros_str_len) (cl:read-byte istream))
      (cl:setf (cl:ldb (cl:byte 8 8) __ros_str_len) (cl:read-byte istream))
      (cl:setf (cl:ldb (cl:byte 8 16) __ros_str_len) (cl:read-byte istream))
      (cl:setf (cl:ldb (cl:byte 8 24) __ros_str_len) (cl:read-byte istream))
      (cl:setf (cl:slot-value msg 'cob_pick_error_string) (cl:make-string __ros_str_len))
      (cl:dotimes (__ros_str_idx __ros_str_len msg)
        (cl:setf (cl:char (cl:slot-value msg 'cob_pick_error_string) __ros_str_idx) (cl:code-char (cl:read-byte istream)))))
  msg
)
(cl:defmethod roslisp-msg-protocol:ros-datatype ((msg (cl:eql '<CobPickResult>)))
  "Returns string type for a message object of type '<CobPickResult>"
  "cob_pick_place_action/CobPickResult")
(cl:defmethod roslisp-msg-protocol:ros-datatype ((msg (cl:eql 'CobPickResult)))
  "Returns string type for a message object of type 'CobPickResult"
  "cob_pick_place_action/CobPickResult")
(cl:defmethod roslisp-msg-protocol:md5sum ((type (cl:eql '<CobPickResult>)))
  "Returns md5sum for a message object of type '<CobPickResult>"
  "678952546c084eaf4429dc029560eb90")
(cl:defmethod roslisp-msg-protocol:md5sum ((type (cl:eql 'CobPickResult)))
  "Returns md5sum for a message object of type 'CobPickResult"
  "678952546c084eaf4429dc029560eb90")
(cl:defmethod roslisp-msg-protocol:message-definition ((type (cl:eql '<CobPickResult>)))
  "Returns full string definition for message of type '<CobPickResult>"
  (cl:format cl:nil "# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======~%##########################################################~%##########     Pickup Result (result)   ######################~%~%std_msgs/Bool success~%~%string cob_pick_error_string~%~%~%================================================================================~%MSG: std_msgs/Bool~%bool data~%~%"))
(cl:defmethod roslisp-msg-protocol:message-definition ((type (cl:eql 'CobPickResult)))
  "Returns full string definition for message of type 'CobPickResult"
  (cl:format cl:nil "# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======~%##########################################################~%##########     Pickup Result (result)   ######################~%~%std_msgs/Bool success~%~%string cob_pick_error_string~%~%~%================================================================================~%MSG: std_msgs/Bool~%bool data~%~%"))
(cl:defmethod roslisp-msg-protocol:serialization-length ((msg <CobPickResult>))
  (cl:+ 0
     (roslisp-msg-protocol:serialization-length (cl:slot-value msg 'success))
     4 (cl:length (cl:slot-value msg 'cob_pick_error_string))
))
(cl:defmethod roslisp-msg-protocol:ros-message-to-list ((msg <CobPickResult>))
  "Converts a ROS message object to a list"
  (cl:list 'CobPickResult
    (cl:cons ':success (success msg))
    (cl:cons ':cob_pick_error_string (cob_pick_error_string msg))
))
