(cl:defpackage cob_camera_sensors-srv
  (:use )
  (:export
   "GETTOFIMAGES"
   "<GETTOFIMAGES-REQUEST>"
   "GETTOFIMAGES-REQUEST"
   "<GETTOFIMAGES-RESPONSE>"
   "GETTOFIMAGES-RESPONSE"
   "ACQUIRECALIBRATIONIMAGES"
   "<ACQUIRECALIBRATIONIMAGES-REQUEST>"
   "ACQUIRECALIBRATIONIMAGES-REQUEST"
   "<ACQUIRECALIBRATIONIMAGES-RESPONSE>"
   "ACQUIRECALIBRATIONIMAGES-RESPONSE"
  ))

