/* Software License Agreement (BSD License)
 *
 * Copyright (c) 2011, Willow Garage, Inc.
 * All rights reserved.
 *
 * Redistribution and use in source and binary forms, with or without
 * modification, are permitted provided that the following conditions
 * are met:
 *
 *  * Redistributions of source code must retain the above copyright
 *    notice, this list of conditions and the following disclaimer.
 *  * Redistributions in binary form must reproduce the above
 *    copyright notice, this list of conditions and the following
 *    disclaimer in the documentation and/or other materials provided
 *    with the distribution.
 *  * Neither the name of Willow Garage, Inc. nor the names of its
 *    contributors may be used to endorse or promote products derived
 *    from this software without specific prior written permission.
 *
 * THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS
 * "AS IS" AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT
 * LIMITED TO, THE IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS
 * FOR A PARTICULAR PURPOSE ARE DISCLAIMED. IN NO EVENT SHALL THE
 * COPYRIGHT OWNER OR CONTRIBUTORS BE LIABLE FOR ANY DIRECT, INDIRECT,
 * INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES (INCLUDING,
 * BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES;
 * LOSS OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER
 * CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT
 * LIABILITY, OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN
 * ANY WAY OUT OF THE USE OF THIS SOFTWARE, EVEN IF ADVISED OF THE
 * POSSIBILITY OF SUCH DAMAGE.
 *
 * Auto-generated by gensrv_cpp from file /home/kerekare/workspace/care-o-bot/src/cob_driver/cob_footprint_observer/srv/GetFootprint.srv
 *
 */


#ifndef COB_FOOTPRINT_OBSERVER_MESSAGE_GETFOOTPRINT_H
#define COB_FOOTPRINT_OBSERVER_MESSAGE_GETFOOTPRINT_H

#include <ros/service_traits.h>


#include <cob_footprint_observer/GetFootprintRequest.h>
#include <cob_footprint_observer/GetFootprintResponse.h>


namespace cob_footprint_observer
{

struct GetFootprint
{

typedef GetFootprintRequest Request;
typedef GetFootprintResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct GetFootprint
} // namespace cob_footprint_observer


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::cob_footprint_observer::GetFootprint > {
  static const char* value()
  {
    return "f40d48f5ad16c4c6dbedafd967306675";
  }

  static const char* value(const ::cob_footprint_observer::GetFootprint&) { return value(); }
};

template<>
struct DataType< ::cob_footprint_observer::GetFootprint > {
  static const char* value()
  {
    return "cob_footprint_observer/GetFootprint";
  }

  static const char* value(const ::cob_footprint_observer::GetFootprint&) { return value(); }
};


// service_traits::MD5Sum< ::cob_footprint_observer::GetFootprintRequest> should match 
// service_traits::MD5Sum< ::cob_footprint_observer::GetFootprint > 
template<>
struct MD5Sum< ::cob_footprint_observer::GetFootprintRequest>
{
  static const char* value()
  {
    return MD5Sum< ::cob_footprint_observer::GetFootprint >::value();
  }
  static const char* value(const ::cob_footprint_observer::GetFootprintRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::cob_footprint_observer::GetFootprintRequest> should match 
// service_traits::DataType< ::cob_footprint_observer::GetFootprint > 
template<>
struct DataType< ::cob_footprint_observer::GetFootprintRequest>
{
  static const char* value()
  {
    return DataType< ::cob_footprint_observer::GetFootprint >::value();
  }
  static const char* value(const ::cob_footprint_observer::GetFootprintRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::cob_footprint_observer::GetFootprintResponse> should match 
// service_traits::MD5Sum< ::cob_footprint_observer::GetFootprint > 
template<>
struct MD5Sum< ::cob_footprint_observer::GetFootprintResponse>
{
  static const char* value()
  {
    return MD5Sum< ::cob_footprint_observer::GetFootprint >::value();
  }
  static const char* value(const ::cob_footprint_observer::GetFootprintResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::cob_footprint_observer::GetFootprintResponse> should match 
// service_traits::DataType< ::cob_footprint_observer::GetFootprint > 
template<>
struct DataType< ::cob_footprint_observer::GetFootprintResponse>
{
  static const char* value()
  {
    return DataType< ::cob_footprint_observer::GetFootprint >::value();
  }
  static const char* value(const ::cob_footprint_observer::GetFootprintResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // COB_FOOTPRINT_OBSERVER_MESSAGE_GETFOOTPRINT_H
