; Auto-generated. Do not edit!


(cl:in-package cob_lookat_action-msg)


;//! \htmlinclude LookAtResult.msg.html

(cl:defclass <LookAtResult> (roslisp-msg-protocol:ros-message)
  ((success
    :reader success
    :initarg :success
    :type cl:boolean
    :initform cl:nil))
)

(cl:defclass LookAtResult (<LookAtResult>)
  ())

(cl:defmethod cl:initialize-instance :after ((m <LookAtResult>) cl:&rest args)
  (cl:declare (cl:ignorable args))
  (cl:unless (cl:typep m 'LookAtResult)
    (roslisp-msg-protocol:msg-deprecation-warning "using old message class name cob_lookat_action-msg:<LookAtResult> is deprecated: use cob_lookat_action-msg:LookAtResult instead.")))

(cl:ensure-generic-function 'success-val :lambda-list '(m))
(cl:defmethod success-val ((m <LookAtResult>))
  (roslisp-msg-protocol:msg-deprecation-warning "Using old-style slot reader cob_lookat_action-msg:success-val is deprecated.  Use cob_lookat_action-msg:success instead.")
  (success m))
(cl:defmethod roslisp-msg-protocol:serialize ((msg <LookAtResult>) ostream)
  "Serializes a message object of type '<LookAtResult>"
  (cl:write-byte (cl:ldb (cl:byte 8 0) (cl:if (cl:slot-value msg 'success) 1 0)) ostream)
)
(cl:defmethod roslisp-msg-protocol:deserialize ((msg <LookAtResult>) istream)
  "Deserializes a message object of type '<LookAtResult>"
    (cl:setf (cl:slot-value msg 'success) (cl:not (cl:zerop (cl:read-byte istream))))
  msg
)
(cl:defmethod roslisp-msg-protocol:ros-datatype ((msg (cl:eql '<LookAtResult>)))
  "Returns string type for a message object of type '<LookAtResult>"
  "cob_lookat_action/LookAtResult")
(cl:defmethod roslisp-msg-protocol:ros-datatype ((msg (cl:eql 'LookAtResult)))
  "Returns string type for a message object of type 'LookAtResult"
  "cob_lookat_action/LookAtResult")
(cl:defmethod roslisp-msg-protocol:md5sum ((type (cl:eql '<LookAtResult>)))
  "Returns md5sum for a message object of type '<LookAtResult>"
  "358e233cde0c8a8bcfea4ce193f8fc15")
(cl:defmethod roslisp-msg-protocol:md5sum ((type (cl:eql 'LookAtResult)))
  "Returns md5sum for a message object of type 'LookAtResult"
  "358e233cde0c8a8bcfea4ce193f8fc15")
(cl:defmethod roslisp-msg-protocol:message-definition ((type (cl:eql '<LookAtResult>)))
  "Returns full string definition for message of type '<LookAtResult>"
  (cl:format cl:nil "# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======~%#result definition~%bool success~%~%~%"))
(cl:defmethod roslisp-msg-protocol:message-definition ((type (cl:eql 'LookAtResult)))
  "Returns full string definition for message of type 'LookAtResult"
  (cl:format cl:nil "# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======~%#result definition~%bool success~%~%~%"))
(cl:defmethod roslisp-msg-protocol:serialization-length ((msg <LookAtResult>))
  (cl:+ 0
     1
))
(cl:defmethod roslisp-msg-protocol:ros-message-to-list ((msg <LookAtResult>))
  "Converts a ROS message object to a list"
  (cl:list 'LookAtResult
    (cl:cons ':success (success msg))
))
