; Auto-generated. Do not edit!


(cl:in-package cob_lookat_action-msg)


;//! \htmlinclude LookAtFeedback.msg.html

(cl:defclass <LookAtFeedback> (roslisp-msg-protocol:ros-message)
  ((status
    :reader status
    :initarg :status
    :type cl:boolean
    :initform cl:nil))
)

(cl:defclass LookAtFeedback (<LookAtFeedback>)
  ())

(cl:defmethod cl:initialize-instance :after ((m <LookAtFeedback>) cl:&rest args)
  (cl:declare (cl:ignorable args))
  (cl:unless (cl:typep m 'LookAtFeedback)
    (roslisp-msg-protocol:msg-deprecation-warning "using old message class name cob_lookat_action-msg:<LookAtFeedback> is deprecated: use cob_lookat_action-msg:LookAtFeedback instead.")))

(cl:ensure-generic-function 'status-val :lambda-list '(m))
(cl:defmethod status-val ((m <LookAtFeedback>))
  (roslisp-msg-protocol:msg-deprecation-warning "Using old-style slot reader cob_lookat_action-msg:status-val is deprecated.  Use cob_lookat_action-msg:status instead.")
  (status m))
(cl:defmethod roslisp-msg-protocol:serialize ((msg <LookAtFeedback>) ostream)
  "Serializes a message object of type '<LookAtFeedback>"
  (cl:write-byte (cl:ldb (cl:byte 8 0) (cl:if (cl:slot-value msg 'status) 1 0)) ostream)
)
(cl:defmethod roslisp-msg-protocol:deserialize ((msg <LookAtFeedback>) istream)
  "Deserializes a message object of type '<LookAtFeedback>"
    (cl:setf (cl:slot-value msg 'status) (cl:not (cl:zerop (cl:read-byte istream))))
  msg
)
(cl:defmethod roslisp-msg-protocol:ros-datatype ((msg (cl:eql '<LookAtFeedback>)))
  "Returns string type for a message object of type '<LookAtFeedback>"
  "cob_lookat_action/LookAtFeedback")
(cl:defmethod roslisp-msg-protocol:ros-datatype ((msg (cl:eql 'LookAtFeedback)))
  "Returns string type for a message object of type 'LookAtFeedback"
  "cob_lookat_action/LookAtFeedback")
(cl:defmethod roslisp-msg-protocol:md5sum ((type (cl:eql '<LookAtFeedback>)))
  "Returns md5sum for a message object of type '<LookAtFeedback>"
  "3a1255d4d998bd4d6585c64639b5ee9a")
(cl:defmethod roslisp-msg-protocol:md5sum ((type (cl:eql 'LookAtFeedback)))
  "Returns md5sum for a message object of type 'LookAtFeedback"
  "3a1255d4d998bd4d6585c64639b5ee9a")
(cl:defmethod roslisp-msg-protocol:message-definition ((type (cl:eql '<LookAtFeedback>)))
  "Returns full string definition for message of type '<LookAtFeedback>"
  (cl:format cl:nil "# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======~%#feedback~%bool status~%#float64 pointing_angle_error~%~%~%~%"))
(cl:defmethod roslisp-msg-protocol:message-definition ((type (cl:eql 'LookAtFeedback)))
  "Returns full string definition for message of type 'LookAtFeedback"
  (cl:format cl:nil "# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======~%#feedback~%bool status~%#float64 pointing_angle_error~%~%~%~%"))
(cl:defmethod roslisp-msg-protocol:serialization-length ((msg <LookAtFeedback>))
  (cl:+ 0
     1
))
(cl:defmethod roslisp-msg-protocol:ros-message-to-list ((msg <LookAtFeedback>))
  "Converts a ROS message object to a list"
  (cl:list 'LookAtFeedback
    (cl:cons ':status (status msg))
))
