; Auto-generated. Do not edit!


(cl:in-package cob_grasp_generation-msg)


;//! \htmlinclude GenerateGraspsResult.msg.html

(cl:defclass <GenerateGraspsResult> (roslisp-msg-protocol:ros-message)
  ((success
    :reader success
    :initarg :success
    :type cl:boolean
    :initform cl:nil)
   (num_grasps
    :reader num_grasps
    :initarg :num_grasps
    :type cl:integer
    :initform 0))
)

(cl:defclass GenerateGraspsResult (<GenerateGraspsResult>)
  ())

(cl:defmethod cl:initialize-instance :after ((m <GenerateGraspsResult>) cl:&rest args)
  (cl:declare (cl:ignorable args))
  (cl:unless (cl:typep m 'GenerateGraspsResult)
    (roslisp-msg-protocol:msg-deprecation-warning "using old message class name cob_grasp_generation-msg:<GenerateGraspsResult> is deprecated: use cob_grasp_generation-msg:GenerateGraspsResult instead.")))

(cl:ensure-generic-function 'success-val :lambda-list '(m))
(cl:defmethod success-val ((m <GenerateGraspsResult>))
  (roslisp-msg-protocol:msg-deprecation-warning "Using old-style slot reader cob_grasp_generation-msg:success-val is deprecated.  Use cob_grasp_generation-msg:success instead.")
  (success m))

(cl:ensure-generic-function 'num_grasps-val :lambda-list '(m))
(cl:defmethod num_grasps-val ((m <GenerateGraspsResult>))
  (roslisp-msg-protocol:msg-deprecation-warning "Using old-style slot reader cob_grasp_generation-msg:num_grasps-val is deprecated.  Use cob_grasp_generation-msg:num_grasps instead.")
  (num_grasps m))
(cl:defmethod roslisp-msg-protocol:serialize ((msg <GenerateGraspsResult>) ostream)
  "Serializes a message object of type '<GenerateGraspsResult>"
  (cl:write-byte (cl:ldb (cl:byte 8 0) (cl:if (cl:slot-value msg 'success) 1 0)) ostream)
  (cl:write-byte (cl:ldb (cl:byte 8 0) (cl:slot-value msg 'num_grasps)) ostream)
  (cl:write-byte (cl:ldb (cl:byte 8 8) (cl:slot-value msg 'num_grasps)) ostream)
  (cl:write-byte (cl:ldb (cl:byte 8 16) (cl:slot-value msg 'num_grasps)) ostream)
  (cl:write-byte (cl:ldb (cl:byte 8 24) (cl:slot-value msg 'num_grasps)) ostream)
)
(cl:defmethod roslisp-msg-protocol:deserialize ((msg <GenerateGraspsResult>) istream)
  "Deserializes a message object of type '<GenerateGraspsResult>"
    (cl:setf (cl:slot-value msg 'success) (cl:not (cl:zerop (cl:read-byte istream))))
    (cl:setf (cl:ldb (cl:byte 8 0) (cl:slot-value msg 'num_grasps)) (cl:read-byte istream))
    (cl:setf (cl:ldb (cl:byte 8 8) (cl:slot-value msg 'num_grasps)) (cl:read-byte istream))
    (cl:setf (cl:ldb (cl:byte 8 16) (cl:slot-value msg 'num_grasps)) (cl:read-byte istream))
    (cl:setf (cl:ldb (cl:byte 8 24) (cl:slot-value msg 'num_grasps)) (cl:read-byte istream))
  msg
)
(cl:defmethod roslisp-msg-protocol:ros-datatype ((msg (cl:eql '<GenerateGraspsResult>)))
  "Returns string type for a message object of type '<GenerateGraspsResult>"
  "cob_grasp_generation/GenerateGraspsResult")
(cl:defmethod roslisp-msg-protocol:ros-datatype ((msg (cl:eql 'GenerateGraspsResult)))
  "Returns string type for a message object of type 'GenerateGraspsResult"
  "cob_grasp_generation/GenerateGraspsResult")
(cl:defmethod roslisp-msg-protocol:md5sum ((type (cl:eql '<GenerateGraspsResult>)))
  "Returns md5sum for a message object of type '<GenerateGraspsResult>"
  "89a93e15e1906977d5060def30025192")
(cl:defmethod roslisp-msg-protocol:md5sum ((type (cl:eql 'GenerateGraspsResult)))
  "Returns md5sum for a message object of type 'GenerateGraspsResult"
  "89a93e15e1906977d5060def30025192")
(cl:defmethod roslisp-msg-protocol:message-definition ((type (cl:eql '<GenerateGraspsResult>)))
  "Returns full string definition for message of type '<GenerateGraspsResult>"
  (cl:format cl:nil "# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======~%#result definition~%bool success~%uint32 num_grasps~%~%~%"))
(cl:defmethod roslisp-msg-protocol:message-definition ((type (cl:eql 'GenerateGraspsResult)))
  "Returns full string definition for message of type 'GenerateGraspsResult"
  (cl:format cl:nil "# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======~%#result definition~%bool success~%uint32 num_grasps~%~%~%"))
(cl:defmethod roslisp-msg-protocol:serialization-length ((msg <GenerateGraspsResult>))
  (cl:+ 0
     1
     4
))
(cl:defmethod roslisp-msg-protocol:ros-message-to-list ((msg <GenerateGraspsResult>))
  "Converts a ROS message object to a list"
  (cl:list 'GenerateGraspsResult
    (cl:cons ':success (success msg))
    (cl:cons ':num_grasps (num_grasps msg))
))
