; Auto-generated. Do not edit!


(cl:in-package cob_grasp_generation-msg)


;//! \htmlinclude QueryGraspsActionGoal.msg.html

(cl:defclass <QueryGraspsActionGoal> (roslisp-msg-protocol:ros-message)
  ((header
    :reader header
    :initarg :header
    :type std_msgs-msg:Header
    :initform (cl:make-instance 'std_msgs-msg:Header))
   (goal_id
    :reader goal_id
    :initarg :goal_id
    :type actionlib_msgs-msg:GoalID
    :initform (cl:make-instance 'actionlib_msgs-msg:GoalID))
   (goal
    :reader goal
    :initarg :goal
    :type cob_grasp_generation-msg:QueryGraspsGoal
    :initform (cl:make-instance 'cob_grasp_generation-msg:QueryGraspsGoal)))
)

(cl:defclass QueryGraspsActionGoal (<QueryGraspsActionGoal>)
  ())

(cl:defmethod cl:initialize-instance :after ((m <QueryGraspsActionGoal>) cl:&rest args)
  (cl:declare (cl:ignorable args))
  (cl:unless (cl:typep m 'QueryGraspsActionGoal)
    (roslisp-msg-protocol:msg-deprecation-warning "using old message class name cob_grasp_generation-msg:<QueryGraspsActionGoal> is deprecated: use cob_grasp_generation-msg:QueryGraspsActionGoal instead.")))

(cl:ensure-generic-function 'header-val :lambda-list '(m))
(cl:defmethod header-val ((m <QueryGraspsActionGoal>))
  (roslisp-msg-protocol:msg-deprecation-warning "Using old-style slot reader cob_grasp_generation-msg:header-val is deprecated.  Use cob_grasp_generation-msg:header instead.")
  (header m))

(cl:ensure-generic-function 'goal_id-val :lambda-list '(m))
(cl:defmethod goal_id-val ((m <QueryGraspsActionGoal>))
  (roslisp-msg-protocol:msg-deprecation-warning "Using old-style slot reader cob_grasp_generation-msg:goal_id-val is deprecated.  Use cob_grasp_generation-msg:goal_id instead.")
  (goal_id m))

(cl:ensure-generic-function 'goal-val :lambda-list '(m))
(cl:defmethod goal-val ((m <QueryGraspsActionGoal>))
  (roslisp-msg-protocol:msg-deprecation-warning "Using old-style slot reader cob_grasp_generation-msg:goal-val is deprecated.  Use cob_grasp_generation-msg:goal instead.")
  (goal m))
(cl:defmethod roslisp-msg-protocol:serialize ((msg <QueryGraspsActionGoal>) ostream)
  "Serializes a message object of type '<QueryGraspsActionGoal>"
  (roslisp-msg-protocol:serialize (cl:slot-value msg 'header) ostream)
  (roslisp-msg-protocol:serialize (cl:slot-value msg 'goal_id) ostream)
  (roslisp-msg-protocol:serialize (cl:slot-value msg 'goal) ostream)
)
(cl:defmethod roslisp-msg-protocol:deserialize ((msg <QueryGraspsActionGoal>) istream)
  "Deserializes a message object of type '<QueryGraspsActionGoal>"
  (roslisp-msg-protocol:deserialize (cl:slot-value msg 'header) istream)
  (roslisp-msg-protocol:deserialize (cl:slot-value msg 'goal_id) istream)
  (roslisp-msg-protocol:deserialize (cl:slot-value msg 'goal) istream)
  msg
)
(cl:defmethod roslisp-msg-protocol:ros-datatype ((msg (cl:eql '<QueryGraspsActionGoal>)))
  "Returns string type for a message object of type '<QueryGraspsActionGoal>"
  "cob_grasp_generation/QueryGraspsActionGoal")
(cl:defmethod roslisp-msg-protocol:ros-datatype ((msg (cl:eql 'QueryGraspsActionGoal)))
  "Returns string type for a message object of type 'QueryGraspsActionGoal"
  "cob_grasp_generation/QueryGraspsActionGoal")
(cl:defmethod roslisp-msg-protocol:md5sum ((type (cl:eql '<QueryGraspsActionGoal>)))
  "Returns md5sum for a message object of type '<QueryGraspsActionGoal>"
  "e01d10fa638d30f8ffca451f7d03e368")
(cl:defmethod roslisp-msg-protocol:md5sum ((type (cl:eql 'QueryGraspsActionGoal)))
  "Returns md5sum for a message object of type 'QueryGraspsActionGoal"
  "e01d10fa638d30f8ffca451f7d03e368")
(cl:defmethod roslisp-msg-protocol:message-definition ((type (cl:eql '<QueryGraspsActionGoal>)))
  "Returns full string definition for message of type '<QueryGraspsActionGoal>"
  (cl:format cl:nil "# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======~%~%Header header~%actionlib_msgs/GoalID goal_id~%QueryGraspsGoal goal~%~%================================================================================~%MSG: std_msgs/Header~%# Standard metadata for higher-level stamped data types.~%# This is generally used to communicate timestamped data ~%# in a particular coordinate frame.~%# ~%# sequence ID: consecutively increasing ID ~%uint32 seq~%#Two-integer timestamp that is expressed as:~%# * stamp.secs: seconds (stamp_secs) since epoch~%# * stamp.nsecs: nanoseconds since stamp_secs~%# time-handling sugar is provided by the client library~%time stamp~%#Frame this data is associated with~%# 0: no frame~%# 1: global frame~%string frame_id~%~%================================================================================~%MSG: actionlib_msgs/GoalID~%# The stamp should store the time at which this goal was requested.~%# It is used by an action server when it tries to preempt all~%# goals that were requested before a certain time~%time stamp~%~%# The id provides a way to associate feedback and~%# result message with specific goal requests. The id~%# specified must be unique.~%string id~%~%~%================================================================================~%MSG: cob_grasp_generation/QueryGraspsGoal~%# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======~%#goal definition~%string object_name~%~%#only return grasp with given id~%#note: cannot be used to return first grasp (id = 0)~%uint32 grasp_id~%~%#only return that many grasps~%#returns all grasps when set to 0~%uint32 num_grasps~%~%#only return graps that have quality >= threshold~%#returns all grasps when set to 0~%float64 threshold~%~%~%~%"))
(cl:defmethod roslisp-msg-protocol:message-definition ((type (cl:eql 'QueryGraspsActionGoal)))
  "Returns full string definition for message of type 'QueryGraspsActionGoal"
  (cl:format cl:nil "# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======~%~%Header header~%actionlib_msgs/GoalID goal_id~%QueryGraspsGoal goal~%~%================================================================================~%MSG: std_msgs/Header~%# Standard metadata for higher-level stamped data types.~%# This is generally used to communicate timestamped data ~%# in a particular coordinate frame.~%# ~%# sequence ID: consecutively increasing ID ~%uint32 seq~%#Two-integer timestamp that is expressed as:~%# * stamp.secs: seconds (stamp_secs) since epoch~%# * stamp.nsecs: nanoseconds since stamp_secs~%# time-handling sugar is provided by the client library~%time stamp~%#Frame this data is associated with~%# 0: no frame~%# 1: global frame~%string frame_id~%~%================================================================================~%MSG: actionlib_msgs/GoalID~%# The stamp should store the time at which this goal was requested.~%# It is used by an action server when it tries to preempt all~%# goals that were requested before a certain time~%time stamp~%~%# The id provides a way to associate feedback and~%# result message with specific goal requests. The id~%# specified must be unique.~%string id~%~%~%================================================================================~%MSG: cob_grasp_generation/QueryGraspsGoal~%# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======~%#goal definition~%string object_name~%~%#only return grasp with given id~%#note: cannot be used to return first grasp (id = 0)~%uint32 grasp_id~%~%#only return that many grasps~%#returns all grasps when set to 0~%uint32 num_grasps~%~%#only return graps that have quality >= threshold~%#returns all grasps when set to 0~%float64 threshold~%~%~%~%"))
(cl:defmethod roslisp-msg-protocol:serialization-length ((msg <QueryGraspsActionGoal>))
  (cl:+ 0
     (roslisp-msg-protocol:serialization-length (cl:slot-value msg 'header))
     (roslisp-msg-protocol:serialization-length (cl:slot-value msg 'goal_id))
     (roslisp-msg-protocol:serialization-length (cl:slot-value msg 'goal))
))
(cl:defmethod roslisp-msg-protocol:ros-message-to-list ((msg <QueryGraspsActionGoal>))
  "Converts a ROS message object to a list"
  (cl:list 'QueryGraspsActionGoal
    (cl:cons ':header (header msg))
    (cl:cons ':goal_id (goal_id msg))
    (cl:cons ':goal (goal msg))
))
