; Auto-generated. Do not edit!


(cl:in-package cob_grasp_generation-msg)


;//! \htmlinclude ShowGraspsFeedback.msg.html

(cl:defclass <ShowGraspsFeedback> (roslisp-msg-protocol:ros-message)
  ((status
    :reader status
    :initarg :status
    :type cl:boolean
    :initform cl:nil))
)

(cl:defclass ShowGraspsFeedback (<ShowGraspsFeedback>)
  ())

(cl:defmethod cl:initialize-instance :after ((m <ShowGraspsFeedback>) cl:&rest args)
  (cl:declare (cl:ignorable args))
  (cl:unless (cl:typep m 'ShowGraspsFeedback)
    (roslisp-msg-protocol:msg-deprecation-warning "using old message class name cob_grasp_generation-msg:<ShowGraspsFeedback> is deprecated: use cob_grasp_generation-msg:ShowGraspsFeedback instead.")))

(cl:ensure-generic-function 'status-val :lambda-list '(m))
(cl:defmethod status-val ((m <ShowGraspsFeedback>))
  (roslisp-msg-protocol:msg-deprecation-warning "Using old-style slot reader cob_grasp_generation-msg:status-val is deprecated.  Use cob_grasp_generation-msg:status instead.")
  (status m))
(cl:defmethod roslisp-msg-protocol:serialize ((msg <ShowGraspsFeedback>) ostream)
  "Serializes a message object of type '<ShowGraspsFeedback>"
  (cl:write-byte (cl:ldb (cl:byte 8 0) (cl:if (cl:slot-value msg 'status) 1 0)) ostream)
)
(cl:defmethod roslisp-msg-protocol:deserialize ((msg <ShowGraspsFeedback>) istream)
  "Deserializes a message object of type '<ShowGraspsFeedback>"
    (cl:setf (cl:slot-value msg 'status) (cl:not (cl:zerop (cl:read-byte istream))))
  msg
)
(cl:defmethod roslisp-msg-protocol:ros-datatype ((msg (cl:eql '<ShowGraspsFeedback>)))
  "Returns string type for a message object of type '<ShowGraspsFeedback>"
  "cob_grasp_generation/ShowGraspsFeedback")
(cl:defmethod roslisp-msg-protocol:ros-datatype ((msg (cl:eql 'ShowGraspsFeedback)))
  "Returns string type for a message object of type 'ShowGraspsFeedback"
  "cob_grasp_generation/ShowGraspsFeedback")
(cl:defmethod roslisp-msg-protocol:md5sum ((type (cl:eql '<ShowGraspsFeedback>)))
  "Returns md5sum for a message object of type '<ShowGraspsFeedback>"
  "3a1255d4d998bd4d6585c64639b5ee9a")
(cl:defmethod roslisp-msg-protocol:md5sum ((type (cl:eql 'ShowGraspsFeedback)))
  "Returns md5sum for a message object of type 'ShowGraspsFeedback"
  "3a1255d4d998bd4d6585c64639b5ee9a")
(cl:defmethod roslisp-msg-protocol:message-definition ((type (cl:eql '<ShowGraspsFeedback>)))
  "Returns full string definition for message of type '<ShowGraspsFeedback>"
  (cl:format cl:nil "# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======~%#feedback~%bool status~%~%~%~%"))
(cl:defmethod roslisp-msg-protocol:message-definition ((type (cl:eql 'ShowGraspsFeedback)))
  "Returns full string definition for message of type 'ShowGraspsFeedback"
  (cl:format cl:nil "# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======~%#feedback~%bool status~%~%~%~%"))
(cl:defmethod roslisp-msg-protocol:serialization-length ((msg <ShowGraspsFeedback>))
  (cl:+ 0
     1
))
(cl:defmethod roslisp-msg-protocol:ros-message-to-list ((msg <ShowGraspsFeedback>))
  "Converts a ROS message object to a list"
  (cl:list 'ShowGraspsFeedback
    (cl:cons ':status (status msg))
))
